# Generated by Django 5.2 on 2025-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_registered_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.PositiveIntegerField(default=0, verbose_name='Registered Participants'),
        ),
    ]
